### ISSUE TITLE
NullReference iotHubHostName of SecurityDaemonClient

### ISSUE THREAD

**Issue by davidzwa** [Azure/event-grid-iot-edge#2]
Tried to run the eventgridmodule in iotedge-dev instead of iotedge. The logs are very explicit about an error:

<pre>
eventgridmodule    | 
eventgridmodule    | Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
eventgridmodule    |    at Microsoft.Azure.EventGridEdge.IotEdge.SecurityDaemonClient..ctor() in /home/vsts/work/1/s/tools/SecurityDaemonClient/SecurityDaemonClient.cs:line 60
eventgridmodule    |    at Microsoft.Azure.EventGridEdge.IoTEdgeHost.IoTEdgeEnvironment..ctor() in /home/vsts/work/1/s/src/IoTEdgeHost/IoTEdgeEnvironment.cs:line 35
eventgridmodule    |    at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program..ctor() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 37
eventgridmodule    |    at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.Main() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 46
eventgridmodule    |    at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.<Main>()
</pre>

Which is in the SecurityDaemonClient:
<pre>
            this.ModuleId = Environment.GetEnvironmentVariable("IOTEDGE_MODULEID");
            this.DeviceId = Environment.GetEnvironmentVariable("IOTEDGE_DEVICEID");
            string iotHubHostName = Environment.GetEnvironmentVariable("IOTEDGE_IOTHUBHOSTNAME");
line 60 -->            this.IotHubName = **iotHubHostName**.Split('.').FirstOrDefault();

            this.moduleGenerationId = Environment.GetEnvironmentVariable("IOTEDGE_MODULEGENERATIONID");
            this.edgeGatewayHostName = Environment.GetEnvironmentVariable("IOTEDGE_GATEWAYHOSTNAME");
            this.workloadApiVersion = Environment.GetEnvironmentVariable("IOTEDGE_APIVERSION");
            string workloadUriString = Environment.GetEnvironmentVariable("IOTEDGE_WORKLOADURI");
</pre>

Could this be the cause? IotHubName not being set?

**Comment by VidyaKukke** [comment]
So those environment variables are expected to be set by IoT deployment. You can do a printenv or inspect on the eventgridmodule to confirm. If unset please open an issue with the iot edge and link this. If the setup is running Linux containers on windows they might come back to say unsupported per I would like to work with you offline and then update this thread after. My alias is vkukkeatmicrosoft.
I can help understand the issue with turning off completely so that you can try it out but obviously never as a production workload as IoT are not supporting it per https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fiot-edge%2Fsupport%23operating-systems&data=02%7C01%7Cvkukke%40microsoft.com%7C5b9b1a05d5e843ffb9ff08d77cd6677a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637115132604179834&sdata=QJxvBECZqlw92PS67LNH12XI3KH05q5C5G%2F3NR8ZCnA%3D&reserved=0

Eventgrid module expects these variables to set and available and crashing is the right behavior for an iot edge module.

**Comment by davidzwa** [comment]
Thanks. This is a variable which probably was not set by the iotedge-dev version, which is a piece of work by itself. Will close the issue, since it is indeed not related to this module.

How do I approach you offline?

**Comment by VidyaKukke** [comment]
> Thanks. This is a variable which probably was not set by the iotedge-dev version, which is a piece of work by itself. Will close the issue, since it is indeed not related to this module.
> How do I approach you offline?

mail me at vkukkeatmicrosoftdotcom.
