### ISSUE TITLE
EventGrid Exception is fired when starting up module

### ISSUE THREAD

**Issue by Fredborg** [Azure/event-grid-iot-edge#9]
When starting up the EventGrid Module on IotEdgeHub Dev, the following Exception is fired in the EventGridModule:

`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.EventGridEdge.IotEdge.SecurityDaemonClient..ctor() in /home/vsts/work/1/s/tools/SecurityDaemonClient/SecurityDaemonClient.cs:line 60
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.IoTEdgeEnvironment..ctor() in /home/vsts/work/1/s/src/IoTEdgeHost/IoTEdgeEnvironment.cs:line 35
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program..ctor() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 37
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.Main() in /home/vsts/work/1/s/src/IoTEdgeHost/Program.cs:line 46
   at Microsoft.Azure.EventGridEdge.IoTEdgeHost.Program.<Main>()`

This is probably because that Environment Variables are missing in the module, since it seems that the SecurityDaemonClient tries to parse these out during startup:

IOTEDGE_MODULEID
IOTEDGE_DEVICEID
IOTEDGE_IOTHUBHOSTNAME
IOTEDGE_MODULEGENERATIONID
IOTEDGE_GATEWAYHOSTNAME
IOTEDGE_APIVERSION
IOTEDGE_WORKLOADURI

This is probaply related to IotEdgeHub Dev simulator, not being working properly. But it makes developers unable to use EventGrid On Edge module, until both teams works out a solution for this.

A suggestion on how to fix this, could be to include those variables in a configuration.json file, which the EventGrid reads, if it cannot find the Environment variables during startup. This configuration file, could be stored along with the persisted metadata on the docker volume.

**Comment by VidyaKukke** [comment]
Thank you for the feedback.  

EventGrid module already retrieves the environment variables to make calls to IoTEdge Security daemon. Being an IoT module the expectation is those variables must exist otherwise the setup is "invalid" IoT Edge setup.

The fact that this expectation is broken in Dev simulator is a bug on IoT Edge team and should definitely be raised. Please do so if not done already. What I'm not sure is if the variables are set somehow. then the requests to Security Daemon will actually succeed. That again has to be tried and followed up with IoT Edge Team.

Regarding the workaround - As far as Event Grid module is concerned you can explicitly set these environment variables during deployment of the module (in the create options). Those will be  read by the module (since it just appears as an environment variable to EG module) and will use it to talk to Security Daemon. Obviously the values have to match what is expected by IoT Security Daemon otherwise request will fail.

Hope this helps.

**Comment by Fredborg** [comment]
Hi,

Thanks for your response - its appreciated.

I agree that the issue is actually with the IoT EdgeHub Dev Team, and I have raised the Issue on their GitHub page here: [https://github.com/Azure/iotedgehubdev/issues/264](https://github.com/Azure/iotedgehubdev/issues/264)

The whole problem is the fact, that IoT EdgeHub dev simulator does not work properly when it comes to Environment Variables. If I set an environment variable in any Module in its CreateOptions section like this:

`             "createOptions": {
                "Env": [
                  "inbound:clientAuth:clientCert:enabled=false",
                  "inbound:serverAuth:tlsPolicy=enabled",
                  "outbound:webhook:httpsOnly=false",
                  "IOTEDGE_MODULEID=EventGrid"
                ],`

It doesnt work. In my startup code of the module, if I Add the Line:

`string moduleId = Environment.GetEnvironmentVariable("IOTEDGE_MODULEID");`

the moduleId variable is null.

We hope to use EventGrid on Edge in the future, when its working properly with the development tools offered by Microsoft.
